<a href="https://colab.research.google.com/github/Prokudinsk/prokudinsk/blob/HW2/HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1 Cчитайте датасет из файла**

In [5]:
#pip install pandas
#pip install numpy
import numpy as np
import pandas as pd
df = pd.read_excel('Реестр_выполненных_рейсов_за_период.xlsx')
df.columns = df.iloc[0]
df = df.drop(0).reset_index(drop=True)
df = df.drop(11268).reset_index(drop=True)
df = df.drop(11268).reset_index(drop=True)
df = df.drop(11268).reset_index(drop=True)
df.dropna(how='all', axis=1, inplace=True)
df.reset_index().tail()

/usr/local/lib/python3.11/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,index,В/П,№ рейса,Код АП,Маршрут,Борт,Время рейса план,Actual data time,ONB and OFB,Компоновка,...,Кл.1,Кл.2,Кл.3,"МВМ, тонн",Тип ВС,АВК,Направление,Катег,Baggage Weight,Spot Number
11263,11263,В,FV 6587,SCW,СЫКТЫВКАР,RA89142,2025-01-31 23:35:00,2025-01-31 23:42:00,2025-01-31 23:29:00,W5Y95,...,0,5,95,45.88,SU9,1,Domestic,J,1083,252
11264,11264,В,FV 6001,IKT,ИРКУТСК,RA73218,2025-01-31 23:00:00,2025-01-31 23:49:00,2025-01-31 23:21:00,Y189,...,0,0,178,79.015,73H,1,Domestic,J,1245,109B
11265,11265,В,FV 6451,TJM,ТЮМЕНЬ,RA73214,2025-01-31 23:40:00,2025-01-31 23:51:00,2025-01-31 23:42:00,C12Y156,...,0,12,153,77,320,1,Domestic,J,759,145
11266,11266,В,DP 515,SVX,ЕКАТЕРИНБУРГ,RA73245,2025-01-31 23:45:00,2025-01-31 23:54:00,2025-01-31 23:49:00,Y189,...,0,0,179,75.296,73H,1,Domestic,J,418,139
11267,11267,В,FV 6161,VKO,ВНУКОВО,RA89062,2025-01-31 23:55:00,2025-01-31 23:58:00,2025-01-31 23:47:00,C12Y75,...,0,8,75,45.88,SU9,1,Domestic,J,254,108A

**2 Выведите основную информацию о датасете: информацию о типах данных, число пропусков, средние значения**

---

In [14]:
print ('\033[1m'+"Информация о типе данных"+'\033[0m')
df.info()
print ('\033[1m'+"\n\n Пропущенные значения"+'\033[0m')
print (df.isna().sum())
print ('\033[1m'+"\n\n Средние значения"+'\033[0m')
print (df.describe())

Информация о типе данных
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11268 entries, 0 to 11267
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   В/П                   11268 non-null  object
 1   № рейса               11268 non-null  object
 2   Код АП                11268 non-null  object
 3   Маршрут               11241 non-null  object
 4   Борт                  11268 non-null  object
 5   Время рейса план      11268 non-null  object
 6   Actual data time      11268 non-null  object
 7   ONB and OFB           11268 non-null  object
 8   Компоновка            11252 non-null  object
 9   Вместимость           11268 non-null  object
 10  Обслужено пассажиров  11266 non-null  object
 11  Взр                   11268 non-null  object
 12  Дети                  11268 non-null  object
 13  До 2-лет              11268 non-null  object
 14  Кл.1                  11268 non-null  object
 15  Кл.2                  11268 non-null  object
 16  Кл.3                  11268 non-null  object
 17  МВМ, тонн             11268 non-null  object
 18  Тип ВС                11268 non-null  object
 19  АВК                   11268 non-null  object
 20  Направление           11268 non-null  object
 21  Катег                 11268 non-null  object
 22  Baggage Weight        11243 non-null  object
 23  Spot Number           11268 non-null  object
dtypes: object(24)
memory usage: 2.1+ MB


 Пропущенные значения
0
В/П                      0
№ рейса                  0
Код АП                   0
Маршрут                 27
Борт                     0
Время рейса план         0
Actual data time         0
ONB and OFB              0
Компоновка              16
Вместимость              0
Обслужено пассажиров     2
Взр                      0
Дети                     0
До 2-лет                 0
Кл.1                     0
Кл.2                     0
Кл.3                     0
МВМ, тонн                0
Тип ВС                   0
АВК                      0
Направление              0
Катег                    0
Baggage Weight          25
Spot Number              0
dtype: int64


 Средние значения
0         В/П  № рейса Код АП      Маршрут     Борт     Время рейса план  \
count   11268    11268  11268        11241    11268                11268
unique      2      820    102          100      628                 6001
top         В  DP  572    SVO  ШЕРЕМЕТЬЕВО  RA73651  2025-01-05 17:10:00
freq     5642       32   1703         1703      165                    7

0          Actual data time          ONB and OFB Компоновка  Вместимость  ...  \
count                 11268                11268      11252        11268  ...
unique                10764                 9767        200           63  ...
top     2025-01-18 22:57:00  2025-01-02 21:13:00     C12Y75          189  ...
freq                      3                    5       2360         2538  ...

0        Кл.1   Кл.2   Кл.3  МВМ, тонн  Тип ВС   АВК   Направление  Катег  \
count   11268  11268  11268   11268.00   11268  11268        11268  11268
unique      9     39    326      58.00      30      1            2      4
top         0      0     75      45.88     SU9      1     Domestic      J
freq    11230   5465    541    3205.00    3378  11268         9370   9667

0      Baggage Weight Spot Number
count           11243       11268
unique           2368         106
top               558        106A
freq               24         553

[4 rows x 24 columns]

/tmp/ipython-input-577444879.py:6: FutureWarning: The behavior of value_counts with object-dtype is deprecated. In a future version, this will *not* perform dtype inference on the resulting index. To retain the old behavior, use `result.index = result.index.infer_objects()`
  print (df.describe())
/tmp/ipython-input-577444879.py:6: FutureWarning: The behavior of value_counts with object-dtype is deprecated. In a future version, this will *not* perform dtype inference on the resulting index. To retain the old behavior, use `result.index = result.index.infer_objects()`
  print (df.describe())
/tmp/ipython-input-577444879.py:6: FutureWarning: The behavior of value_counts with object-dtype is deprecated. In a future version, this will *not* perform dtype inference on the resulting index. To retain the old behavior, use `result.index = result.index.infer_objects()`
  print (df.describe())

**3 Посчитайте процент выполненных рейсов по каждому из аэропортов (Код АП), выведите топ-10 результатов**

---

In [18]:
df.per = df['Код АП'].value_counts(normalize=True).mul(100)
df.per.head(10).reset_index()

  Код АП  proportion
0    SVO   15.113596
1    VKO    9.300674
2    KGD    5.928293
3    AER    3.851615
4    KZN    3.248136
5    MMK    2.902023
6    SVX    2.786652
7    ARH    2.777778
8    KUF    2.405041
9    UFA    2.174299

**4 Посчитайте процент выполненных рейсов ВВЛ по каждому из аэропортов (Код АП), выведите топ-10 результатов**

---

In [20]:
df.perdom = df.loc[df['Направление'] == 'Domestic', 'Код АП'].value_counts(normalize=True).mul(100)
df.perdom.head(10).reset_index()

  Код АП  proportion
0    SVO   18.175027
1    VKO   11.184632
2    KGD    7.129136
3    AER    4.631804
4    KZN    3.906083
5    MMK    3.489861
6    SVX    3.351121
7    ARH    3.340448
8    KUF    2.892209
9    UFA    2.614728

**5 Выведите самый популярный маршрут по каждому из направлений (Domestic/International)**


---

In [27]:
#select = "International" # @param ["Domestic", "International"]
airport_count = df.loc[df['Направление'] == "Domestic", 'Код АП'].value_counts().reset_index()
airport_count.columns = ['Код АП', 'Кол-во рейсов']
airport_max = airport_count['Кол-во рейсов'].max()
airport_best = airport_count[airport_count['Кол-во рейсов'] == airport_max]['Код АП']
print ('\033[1m'+'Самый популярный маршрут Domestic:' +'\033[0m', ','.join(airport_best))

airport_count = df.loc[df['Направление'] == "International", 'Код АП'].value_counts().reset_index()
airport_count.columns = ['Код АП', 'Кол-во рейсов']
airport_max = airport_count['Кол-во рейсов'].max()
airport_best = airport_count[airport_count['Кол-во рейсов'] == airport_max]['Код АП']
print ('\033[1m'+'Самый популярный маршрут International:' +'\033[0m', ','.join(airport_best))

Самый популярный маршрут Domestic: SVO
Самый популярный маршрут International: IST

**6 Выведите часть таблицы с рейсами категории C и маршрутом САЛЕХАРД**

---

In [36]:
df1 = df.dropna().copy()
df1["Baggage Weight"] = df1["Baggage Weight"].astype(int)
list_c = df1.loc[((df['Код АП'] == "SLY") & (df1['Катег'] == "C"))]
list_c

,В/П,№ рейса,Код АП,Маршрут,Борт,Время рейса план,Actual data time,ONB and OFB,Компоновка,Вместимость,...,Кл.1,Кл.2,Кл.3,"МВМ, тонн",Тип ВС,АВК,Направление,Катег,Baggage Weight,Spot Number
8941,П,YC 9715,SLY,САЛЕХАРД,67219,2025-01-24 19:00:00,2025-01-24 19:30:00,2025-01-24 19:34:00,14,19,...,0,6,0,24.04,CR2,1,Domestic,C,40,262
9511,В,YC 9716,SLY,САЛЕХАРД,RA67219,2025-01-26 14:00:00,2025-01-26 14:04:00,2025-01-26 14:02:00,C14,19,...,0,0,5,24.04,CR2,1,Domestic,C,180,262

**7 Выведите на экран результат из пункта выше с сортировкой по убыванию Baggage Weight**

In [37]:
sort_list = df1.loc[((df['Код АП'] == "SLY") & (df1['Катег'] == "C"))].sort_values(by='Baggage Weight', ascending=[False])
sort_list

,В/П,№ рейса,Код АП,Маршрут,Борт,Время рейса план,Actual data time,ONB and OFB,Компоновка,Вместимость,...,Кл.1,Кл.2,Кл.3,"МВМ, тонн",Тип ВС,АВК,Направление,Катег,Baggage Weight,Spot Number
9511,В,YC 9716,SLY,САЛЕХАРД,RA67219,2025-01-26 14:00:00,2025-01-26 14:04:00,2025-01-26 14:02:00,C14,19,...,0,0,5,24.04,CR2,1,Domestic,C,180,262
8941,П,YC 9715,SLY,САЛЕХАРД,67219,2025-01-24 19:00:00,2025-01-24 19:30:00,2025-01-24 19:34:00,14,19,...,0,6,0,24.04,CR2,1,Domestic,C,40,262

**8 Выведите среднюю МВМ и Вместимость с группировкой по направлению и типу ВС**

---

In [38]:
direct_and_type = df.groupby(['Направление','Тип ВС'])
list_group = direct_and_type.agg({
    'Вместимость': 'mean',
    'МВМ, тонн': 'mean'
})
print(list_group)

0                    Вместимость   МВМ, тонн
Направление   Тип ВС
Domestic      319     128.208817   70.077146
              320     158.302013    76.40604
              321     215.638298   89.170213
              32A     151.274538        75.5
              32B     189.848485   91.113636
              32N     176.170732   75.213415
              32Q     237.549708   93.520468
              332      361.47619       233.0
              333     298.692308  233.365385
              735          126.0       56.85
              73G          140.0       70.08
              73H     188.229361   76.871667
              73W          148.0   67.269776
              77W     420.333333     325.074
              789          290.0     250.836
              A26           40.0        24.0
              CR1           50.0       24.04
              CR2           49.5   24.034194
              E90          110.0        50.3
              S9S           93.0       45.88
              SU9      90.282105   46.103326
              YK4           30.0        17.2
International 319     132.700565   69.751412
              320     159.610619   76.225664
              321          190.0        89.0
              32A          148.0   75.184211
              32B          214.0   89.533333
              32N     181.947368   76.964912
              32Q     223.879828    93.51073
              332     287.278689  234.245902
              333     302.725664  233.238938
              733          148.0      63.134
              735          123.0   56.233333
              739          184.0      85.139
              73H      174.54251   78.344777
              73W          120.0     69.5125
              752          238.0     115.892
              763         313.75     186.313
              772          429.5    289.4485
              77W          354.0      351.03
              789          290.0   243.90096
              7M8     166.848485       82.19
              E75           76.0       38.79
              E95          107.0       50.79
              SU9          100.0       49.45